# Generated by Django 3.1.3 on 2020-11-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
