# Generated by Django 3.1.3 on 2020-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_galeria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='insumos'),
        ),
    ]
