# Generated by Django 3.1.3 on 2020-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_insumos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
            ],
        ),
    ]
