# Generated by Django 3.1.3 on 2020-11-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_misionvision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='descripcion',
            field=models.TextField(max_length=205),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(max_length=125),
        ),
    ]
