# Generated by Django 3.1.2 on 2020-12-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201125_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='correo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencias']]),
        ),
    ]
