# Generated by Django 3.1.2 on 2021-05-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_insumos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='precio',
        ),
    ]
