# Generated by Django 3.1.2 on 2021-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_insumos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='descripcion',
            field=models.TextField(default=1, max_length=205),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumos',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
