# Generated by Django 3.1.2 on 2021-05-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210519_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.DeleteModel(
            name='MisionVision',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
